workflows:
  ios_telegram:
    name: Telegram iOS Bazel Build
    max_build_duration: 120
    environment:
      groups:
        - certificate_credentials
      vars:
        BAZEL_CACHE: "/Users/builder/.bazel-cache"
      xcode: 15.0

    scripts:
      - name: Install Bazelisk
        script: |
          brew install bazelisk
          bazelisk version

      - name: Build Telegram iOS
        script: |
          bazelisk build \
            --config=ios_fat \
            //Telegram:Telegram

      - name: Export IPA
        script: |
          mkdir -p build/ipa
          cp bazel-bin/Telegram/Telegram.ipa build/ipa/Telegram.ipa

    artifacts:
      - build/ipa/*.ipa
