workflows:
  ios_telegram:
    name: Telegram iOS Bazel Build
    max_build_duration: 120
    environment:
      xcode: latest
    scripts:
      - name: Init submodules
        script: |
          git submodule update --init --recursive

      - name: Build Telegram iOS
        script: |
          ./build-system/build.sh ios
